SystemSettings : "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf" {
 Systems {
  SCR_GarbageSystem "{5F10E7EA29B0EDEC}" {
   Rules {
    EntityClassGarbageRule "{60713063DB480AC7}" {
     Lifetime 120
    }
    ComponentClassGarbageRule "{6071306334D2708C}" {
     Lifetime 150
    }
    EntityClassGarbageRule "{60713063F62751A3}" {
     Lifetime 500
    }
   }
  }
 }
}