SCR_LoadoutSaveBlackListHolder {
 m_LoadoutSaveBlackLists {
  SCR_LoadoutSaveBlackList "{6708A08C204E5C2D}" {
   m_aBlackListedPrefabs {
    "{1663496AE5B9F10B}Prefabs/Weapons/Ammo/Ammo_Grenade_HEDP_M433.et"
   }
  }
  SCR_LoadoutSaveBlackList "{6708A08C204E5C3C}" {
   m_bBlackListActive 1
   m_aBlackListedPrefabs {
    "{7A82FE978603F137}Prefabs/Weapons/Launchers/RPG7/Launcher_RPG7.et"
    "{E8A55396050E1762}Prefabs/Weapons/Launchers/RPG7/Launcher_RPG7_pgo7.et"
    "{3F38EE51E904AE5B}Prefabs/Weapons/Launchers/RPOA/Launcher_RPOA.et"
    "{D107989BCA4445D7}Prefabs/Weapons/Launchers/RPOA/Launcher_RPOD.et"
    "{7C45EC94C698246B}Prefabs/Weapons/Launchers/RPG75/Launcher_RPG75.et"
    "{722CE6FEC39EE896}Prefabs/Weapons/Launchers/RPG22/Launcher_RPG22.et"
    "{9C5C20FB0E01E64F}Prefabs/Weapons/Launchers/M72/Launcher_M72A3.et"
    "{2C935EF6F98E6354}Prefabs/Weapons/Magazines/MK153/Container_MK153_HEAA.et"
    "{27AC9FC7F5E2BEEB}Prefabs/Weapons/Magazines/MK153/Container_MK153_HEDP.et"
    "{319873694735DE0F}Prefabs/Weapons/Magazines/MK153/Container_MK153_NE.et"
    "{35022055DCDDE98B}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2.et"
    "{DB53366D8C521124}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2_NoMBS.et"
    "{958E88913CBDD0BF}Prefabs/Weapons/Launchers/RPG7/Launcher_RPG7_1pn93.et"
    "{D6BC90F8AE0AB8EF}Prefabs/Weapons/Launchers/RPG7/Launcher_RPG7_pgo7_rhs.et"
    "{E0CFA3FE78FC5190}Prefabs/Weapons/Launchers/M72/Launcher_LAW66_L1A1.et"
    "{65DEE4A3BAAD1B1E}Prefabs/Weapons/Launchers/LAW80/Launcher_LAW80_base.et"
    "{3265C13DC700E7FE}Prefabs/Weapons/Launchers/MAW_84MM/Launcher_84mm_MAW.et"
    "{AE8BF1F7476AA76D}Prefabs/Weapons/Launchers/MAW_84MM/Launcher_84mm_MAW_Optic.et"
    "{F2E474689BD7C2E1}Prefabs/Weapons/Ammo/Ammo_Rocket_HEAT_L40.et"
   }
  }
  SCR_LoadoutSaveBlackList "{6708A08C2048BA1E}" {
   m_bBlackListActive 1
   m_aBlackListedPrefabs {
    "{B05A816C0BF50802}Prefabs/Weapons/Explosives/Mine_PMN4/Mine_PMN4.et"
    "{D6EF54367CECE1D9}Prefabs/Weapons/Explosives/Mine_TM62M/Mine_TM62M.et"
    "{97064F8597F2D7BF}Prefabs/Weapons/Explosives/DemoBlock_TSh400g/DemoBlock_TSh400g.et"
    "{33CBDE73AB48172A}Prefabs/Weapons/Explosives/DemoBlock_M112/DemoBlock_M112.et"
    "{49FFE8F373F55960}Prefabs/Weapons/Explosives/Mine_M15AT/Mine_M15AT.et"
   }
  }
  SCR_LoadoutSaveBlackList "{6708A08C204B3AA0}" {
   m_aBlackListedPrefabs {
    "{38BAE094333E31BF}Prefabs/Weapons/Ammo/Ammo_Shell_81mm_HE_M821.et"
    "{98EC9C526AFBA282}Prefabs/Weapons/Ammo/Ammo_Shell_82mm_HE_O832DU.et"
   }
  }
 }
 m_aSaveBlackListItems {
  SCR_LoadoutSaveBlackListItem "{68E8B45E03DEAA66}" {
   m_sSaveBlackListItem "{144AA3DABB80974C}Prefabs/Weapons/Tripods/9K135/Part_9K135TB_Launcher.et"
  }
  SCR_LoadoutSaveBlackListItem "{68E8B45FD534A625}" {
   m_sSaveBlackListItem "{DE25A434026D99AC}Prefabs/Weapons/Tripods/BGM71TOW/Part_BGM-71D_Launcher.et"
  }
  SCR_LoadoutSaveBlackListItem "{68E8B45E3C37D76B}" {
   m_sSaveBlackListItem "{B0A890995104A02D}Prefabs/Weapons/Tripods/9K135/Part_9K135_Launcher.et"
  }
  SCR_LoadoutSaveBlackListItem "{68E8B4606F4B3557}" {
   m_sSaveBlackListItem "{95544A428439B73E}Prefabs/Weapons/Magazines/2B9/Magazine__82mm_2B9_HE.et"
  }
 }
}