SCR_XPRewardList : "{8227B4636C73C5B5}Configs/Campaign/CampaignXPRewards.conf" {
 m_aRewardList {
  SCR_XPRewardInfo "{51C6A3459A34BAE8}" {
   m_iRewardXP 50
  }
  SCR_XPRewardInfo "{5E0E812546D6087F}" {
   m_iRewardXP 50
  }
  SCR_XPRewardInfo "{62B2880A2E7E5E4D}" {
   m_iRewardXP -100
  }
  SCR_XPRewardInfo "{51BC713EEC1AF2F5}" {
   m_iRewardXP 25
  }
  SCR_XPRewardInfo "{5938830DDD888A92}" {
   m_iRewardXP 30
  }
  SCR_XPRewardInfo "{6576AE33559DC206}" {
   m_iRewardXP 50
  }
  SCR_XPRewardInfo "{6658A2D7236CA062}" {
   m_iRewardXP -5
  }
  SCR_XPRewardInfo "{666662E1EE080C87}" {
   m_iRewardXP 5
  }
 }
}