SCR_MissionHeaderCampaign {
 World "{D610C0DCB827D014}Worlds/Barzan/Barzan.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Barzan"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{7AE135CC6B065F0E}Images/Reforger_Conflict_map_Barzan.edds"
 m_sLoadingScreen "{7AE135CC6B065F0E}Images/Reforger_Conflict_map_Barzan.edds"
 m_sPreviewImage "{7AE135CC6B065F0E}Images/Reforger_Conflict_map_Barzan.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{6916B4DD1FA4EA42}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}