SCR_MissionHeaderCampaign {
 World "{FC9BC4DFEE126C66}Worlds/Fallujah/Fallujah_01.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Fallujah"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{855DE4E02F191796}art/FallujahApresentation.edds"
 m_sLoadingScreen "{855DE4E02F191796}art/FallujahApresentation.edds"
 m_sPreviewImage "{855DE4E02F191796}art/FallujahApresentation.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{69685265C934F478}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}