SCR_MissionHeaderCampaign {
 World "{2429FF7FD73D3572}Worlds/Belleau Wood/Belleau Wood 02/Belleau Wood 02.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Belleau Wood 3t"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{83571E25709E66A9}Images/Reforger_Conflict_map_Bellau-Wood_02.edds"
 m_sLoadingScreen "{83571E25709E66A9}Images/Reforger_Conflict_map_Bellau-Wood_02.edds"
 m_sPreviewImage "{83571E25709E66A9}Images/Reforger_Conflict_map_Bellau-Wood_02.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{6A6E900CB26DDD49}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}