SCR_MissionHeaderCampaign {
 World "{69247F48EB154EBF}Worlds/Belleau Wood/Belleau Wood 03/Belleau Wood 03.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Belleau Wood "
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{775F59BD7D430EDD}Images/Reforger_Conflict_map_Bellau-Wood_03.edds"
 m_sLoadingScreen "{775F59BD7D430EDD}Images/Reforger_Conflict_map_Bellau-Wood_03.edds"
 m_sPreviewImage "{775F59BD7D430EDD}Images/Reforger_Conflict_map_Bellau-Wood_03.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{6A6EBC1202ACF5C2}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}