SCR_MissionHeaderCampaign {
 World "{43CA30D66155A438}Worlds/Enden/Northern Everon/Northern_Everon_0.1.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Northern Everon"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{0944CA87FBB79A1F}Images/Reforger_Conflict_map_North_Everon_01.edds"
 m_sLoadingScreen "{0944CA87FBB79A1F}Images/Reforger_Conflict_map_North_Everon_01.edds"
 m_sPreviewImage "{0944CA87FBB79A1F}Images/Reforger_Conflict_map_North_Everon_01.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{69451B9A802021CA}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}