SCR_MissionHeaderCampaign {
 World "{1E4D88D0CDE4AE43}Worlds/Zargabad/Zargabad_02/Zargabad_02.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Zargabad 5t"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{C2D2020E5635536E}Images/Reforger_Conflict_map_Zargabad_01.edds"
 m_sLoadingScreen "{C2D2020E5635536E}Images/Reforger_Conflict_map_Zargabad_01.edds"
 m_sPreviewImage "{C2D2020E5635536E}Images/Reforger_Conflict_map_Zargabad_01.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{6916B4DDB83CB57E}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}