SCR_MissionHeaderCampaign {
 World "{5BDD974763FC9266}Worlds/Kolguyev/Kolguyev_v01.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Kolguyev"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{2937144185C0A985}Images/Reforger_Conflict_map_Kolguyev_01.edds"
 m_sLoadingScreen "{2937144185C0A985}Images/Reforger_Conflict_map_Kolguyev_01.edds"
 m_sPreviewImage "{2937144185C0A985}Images/Reforger_Conflict_map_Kolguyev_01.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{693D1AA50D652307}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}